import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import {
  NavigationChevron,
  NavigationMenu,
  NavigationMenuContent,
  NavigationMenuItem,
  NavigationMenuList,
  NavigationMenuSub,
  NavigationMenuTrigger,
  navigationMenuTriggerStyle,
  NavigationMenuViewport,
} from "@/components/ui/navigation-menu";

import { Card } from "@/components/ui/card";

import { Logo } from "@/components/logo";
import { Search } from "lucide-react";
import { Button } from "@/components/ui/button";
import { MenuItem, menuItems } from "../lib/menuItems";
import { cn } from "@/lib/utils";
import { NavIconMenu } from "@/lib/navIconMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const openSans = Open_Sans({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${openSans.className} antialiased bg-primary`}>
        <div className="z-20 bg-primary shadow flex justify-center text-primary-foreground w-full py-2 sticky top-0">
          <NavigationMenu className="grow max-w-screen-xl px-2 flex gap-2 items-center">
            <div className="h-10 px-4">
              <Link href="/">
                <Logo />
              </Link>
            </div>

            <NavigationMenuList>
              <div className="absolute"></div>

              <NavigationMenuItem>
                <Card className="relative bg-primary-foreground/10 hover:bg-primary-foreground/20 border-border/20 rounded-md">
                  <NavigationMenuTrigger className="relative !text-primary-foreground !bg-transparent items-center py-1">
                    <div className="text-left flex flex-col">
                      <div className="leading-none text-sm">Bekijk ons</div>
                      <div className="flex gap-1 items-center text-base">
                        <div className="font-bold leading-none align-bottom">Assortiment</div>
                        <NavigationChevron strokeWidth={3} />
                      </div>
                    </div>
                  </NavigationMenuTrigger>
                  <div className="absolute mt-2 rounded-lg w-fit h-fit shadow overflow-hidden">
                    <NavigationMenuViewport className="transition-all" />
                  </div>
                </Card>
                <NavigationMenuContent className="">
                  <SubMenu items={menuItems} noSeparator />
                </NavigationMenuContent>
              </NavigationMenuItem>
            </NavigationMenuList>

            <div className="self-stretch bg-card text-card-foreground text-sm grow rounded-md flex gap-2 items-center p-1">
              <Button variant="ghost" className="text-muted-foreground">
                <Search />
              </Button>
              Zoeken
            </div>

            <NavIconMenu />
          </NavigationMenu>
        </div>

        <div className="relative bg-background">{children}</div>
      </body>
    </html>
  );
}

const SubMenu = ({ items, title, noSeparator }: { items: MenuItem[]; title?: string; noSeparator?: boolean }) => {
  return (
    <NavigationMenuSub orientation="vertical">
      <div className={cn("flex items-start h-full", noSeparator ? "" : "border-l")}>
        <NavigationMenuList className="flex flex-col items-stretch p-1">
          {title && (
            <Link
              href={""}
              className={cn(navigationMenuTriggerStyle(), "w-full text-nowrap flex justify-start font-bold")}
            >
              {title}
            </Link>
          )}
          {items.map(({ title, href, subItems }) => {
            const itemClass = "w-full text-left text-nowrap flex gap-4 justify-between";

            return (
              <NavigationMenuItem key={href} value={href}>
                {subItems?.length ? (
                  <NavigationMenuTrigger className={itemClass}>
                    {title}
                    <div className="text-muted-foreground">
                      <NavigationChevron orientation="horizontal" />
                    </div>
                  </NavigationMenuTrigger>
                ) : (
                  <Link href={href} className={cn(navigationMenuTriggerStyle(), itemClass)}>
                    {title}
                  </Link>
                )}

                {subItems?.length && (
                  <NavigationMenuContent className="flex flex-col items-stretch p-1 h-full">
                    <SubMenu items={subItems} title={title} />
                  </NavigationMenuContent>
                )}
              </NavigationMenuItem>
            );
          })}
        </NavigationMenuList>

        <div className="self-stretch p-0">
          <NavigationMenuViewport className="h-fit min-h-[calc(100%+8px)] ml-[-4px] m-[-4px] pb-2 relative items-start border-none bg-transparent shadow-none" />
        </div>
      </div>
    </NavigationMenuSub>
  );
};
